### PR TITLE
Fix README.md

### PR DESCRIPTION
**Pull request by v1rtl**

### CODE REVIEW

**Comment by clayrisser** [comment]
I would like to keep the dependancies section. If you don't have NodeJS on your computer this program won't work.

**Comment by v1rtl** [comment]
@codejamninja, **dependency** sounds confusing because ppl first think of npm dependencies. I'll rename it to "Requirements"

**Comment by clayrisser** [comment]
You make a good point. Renaming it to be more precise is good. Maybe `System Requirements`??? Thanks

**Comment by clayrisser** [comment]
Thanks

**Comment by v1rtl** [comment]
Nice!

**Pull request merged**
